# Generated by Django 4.0.2 on 2022-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_7',
            new_name='photo_main',
        ),
    ]
